name: $(date:yyyyMMdd)$(rev:.rr) #20191214.10

trigger:
  - master


stages:
  - stage: compile
    jobs:
      - job: aspnet
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet build ./P2Translator.sln
  - stage: test
    jobs:
      - job: aspnet_test
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet test ./P2Translator.sln --logger trx --collect:"XPlat Code Coverage"
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: cobertura
              summaryFileLocation: '**/TestResults/*/coverage.cobertura.xml'
  - stage: analyze
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '3.1.100'
          - script: dotnet tool install --global dotnet-sonarscanner
          - script: |
              dotnet sonarscanner begin \
              /k:p2-translator-team \
              /d:sonar.login=$SONAR_TOKEN \
              /d:sonar.host.url=https://sonarcloud.io/ \
              /d:sonar.javascript.exclusions=**/P2Translator.Client/wwwroot/** \
              /d:sonar.coverage.exclusions=**/P2Translator.Client/wwwroot/** \
              /d:sonar.cs.opencover.reportsPaths=**/P2Translator.Testing/coverage.opencover.xml \
              /d:sonar.cs.vstest.reportsPaths=**/*.trx \
              /o:1910-oct21-dotnet
              dotnet build ./P2Translator.sln
              dotnet test ./P2Translator.sln --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
              dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN
            env:
              SONAR_TOKEN: $(SONAR_LOGIN)

  - stage: pack
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: docker image build -f ./dockerfile -t revaturep2translator/p2translator:$BUILD_NAME .
            env:
              BUILD_NAME: $(Build.DefinitionName)
          - script: docker login --username $DOCKER_USER --password $DOCKER_TOKEN
            env:
              DOCKER_TOKEN: $(docker.token)
              DOCKER_USER: $(docker.user)
          - script: docker image push revaturep2translator/p2translator:$BUILD_NAME
            env:
              BUILD_NAME: $(Build.DefinitionName)